site_name: DDS documentation

docs_dir: doc_source
site_dir: docs

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      include_source: True

theme:
  name: "readthedocs"

nav:
    - Home: index.md
    - Reference: dds-reference.md
    - Tutorial - scikit-learn: test_sklearn.ipynb
    - Tutorial - plotting: plotting.ipynb
