site_name: DDS documentation

docs_dir: doc_source
site_dir: docs

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      include_source: True
      execute: True

extra_css: [extra.css]

theme:
  name: "readthedocs"

nav:
    - Home: index.md
    - Reference: dds-reference.md
    - FAQ: faq.md
    - Tutorial: tutorial.ipynb
    - Tutorial - modules: tut_modules.ipynb
    - Tutorial - plotting: plotting.ipynb
    - Tutorial - collaboration: tut_collab.ipynb
    - Tutorial - scikit-learn: test_sklearn.ipynb
    - Tutorial - custome types: tut_custom_types.ipynb
