site_name: DDS documentation

docs_dir: doc_source
site_dir: docs

plugins:
  - search
  # - mkdocstrings:
  #     handlers:
  #       python:
  #         paths: [., .., ./dds, ../dds]
  #         rendering:
  #           show_category_heading: true
  #           show_root_toc_entry: false
  - mkdocs-jupyter:
      include_source: True
      execute: True
  - exclude:
      glob:
        - "*.py"
        - "jupyter/*"



extra_css: [extra.css]

theme:
  name: "readthedocs"

nav:
    - Home: index.md
    - User guide: user_guide.ipynb
#    - Reference: dds-reference.md
    - Collaboration and branching: tut_collab.ipynb
    - Working with modules: tut_modules.ipynb
    - Plotting dependencies: tut_plotting.ipynb
    - Adding custom types: tut_custom_types.ipynb
    - Tutorial - scikit-learn: tut_sklearn.ipynb
    - FAQ: faq.md
    - Changelog: changelog.md
